### ISSUE TITLE
CRD are not deleted after chart uninstallation

### ISSUE THREAD

**Issue by eshepelyuk** [datawire/ambassador-chart#15]
I installed chart then uninstalled it, deleted corresponding ns.
but CRD are still there

```
$ kubectl get crd --all-namespaces | grep ambassador
authservices.getambassador.io                  2020-01-17T17:58:17Z
consulresolvers.getambassador.io               2020-01-17T17:58:17Z
filterpolicies.getambassador.io                2020-01-17T17:58:17Z
filters.getambassador.io                       2020-01-17T17:58:17Z
hosts.getambassador.io                         2020-01-17T17:58:17Z
kubernetesendpointresolvers.getambassador.io   2020-01-17T17:58:17Z
kubernetesserviceresolvers.getambassador.io    2020-01-17T17:58:17Z
logservices.getambassador.io                   2020-01-17T17:58:17Z
mappings.getambassador.io                      2020-01-17T17:58:17Z
modules.getambassador.io                       2020-01-17T17:58:17Z
ratelimits.getambassador.io                    2020-01-17T17:58:17Z
ratelimitservices.getambassador.io             2020-01-17T17:58:17Z
tcpmappings.getambassador.io                   2020-01-17T17:58:17Z
tlscontexts.getambassador.io                   2020-01-17T17:58:18Z
tracingservices.getambassador.io               2020-01-17T17:58:18Z
```

I believe CRD should be pruned on chart uninstallation.

**Comment by nbkrause** [comment]
What version of Helm are you using? 

Helm 2 should delete the crds if you set `crds.keep: false`.

Helm 3 does not remove CRDs.

**Comment by eshepelyuk** [comment]
I'm using Helm3

**Comment by nbkrause** [comment]
This is a limitation of Helm (see https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you)

If you need CRDs removed with the chart, I would recommend writing a wrapper around helm that deletes the crds when the chart is uninstalled or just doing it manually.

I currently use a simple script that takes a substring of the CRD name (getambassador) and removes all the CRDs that match that substring.
```
#!/bin/bash

for crd in $(kubectl get crds -o name);
do
  if [[ $(echo $crd | grep $1) != "" ]];
  then
    kubectl delete $crd
  fi
done
```

Closing since this is not an issue with the Ambassador Chart.
