### ISSUE TITLE
Revisit CI testing

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador-chart#87]
There is much to be desired with our current CI tests for the helm chart.

We should revisit how we are doing linting and testing so they are less flakey. We could possibly implement this https://github.com/helm/chart-testing which seems to be a standard for helm chart CI tests.

**Comment by inercia** [comment]
Added the [chart-testing GitHub action](https://github.com/helm/chart-testing-action) in [this PR](https://github.com/datawire/ambassador-chart/pull/101). This should run tests automatically in every PR.

**Comment by inercia** [comment]
Added some yaml files for testing different configurations with the Helm chart. See the YAML files in [this directory](https://github.com/datawire/ambassador-chart/tree/master/ci).

We should evaluate how to remove the Travis job (or maybe get rid of some of the code there...)

**Comment by acookin** [comment]
Closing this issue as it seems it was resolved by https://github.com/datawire/ambassador-chart/pull/101 

the travis job is a part of the release process, and since the release process is likely going to change a bit as a result of https://github.com/datawire/apro/issues/1280, i think it's okay to punt on that.
